AIDemo.o: AIDemo.cc Player.hh Utils.hh BackTrace.hh PosDir.hh Board.hh \
 Action.hh Registry.hh
AIJRivaille.o: AIJRivaille.cc Player.hh Utils.hh BackTrace.hh PosDir.hh \
 Board.hh Action.hh Registry.hh
AINull.o: AINull.cc Player.hh Utils.hh BackTrace.hh PosDir.hh Board.hh \
 Action.hh Registry.hh
Action.o: Action.cc Action.hh Utils.hh BackTrace.hh PosDir.hh Board.hh
BackTrace.o: BackTrace.cc BackTrace.hh
Board.o: Board.cc Board.hh Utils.hh BackTrace.hh PosDir.hh Action.hh
Game.o: Game.cc Game.hh Utils.hh BackTrace.hh PosDir.hh Board.hh \
 Action.hh Player.hh Registry.hh
Main.o: Main.cc Game.hh Utils.hh BackTrace.hh PosDir.hh Board.hh \
 Action.hh Player.hh Registry.hh
Player.o: Player.cc Player.hh Utils.hh BackTrace.hh PosDir.hh Board.hh \
 Action.hh Registry.hh
PosDir.o: PosDir.cc PosDir.hh Utils.hh BackTrace.hh
Registry.o: Registry.cc Registry.hh Utils.hh BackTrace.hh
Utils.o: Utils.cc Utils.hh BackTrace.hh
